# Assignment 1 IRS

In [2]:
# required imports
import numpy as np
import fnmatch
import os


Suppose we have 3 files containing data :

### File Contents

<img src="1.png"/>
<img src="2.png"/>
<img src="3.png"/>

# Step 1 Create Files with Dummy data

You have to create few files with dummy data of your own choice as shown above.

# Step 2 Traverse Directories

 Now, You have to traverse the directories and store all the files into a dict type variable(files_dict). 

In [3]:
# Here we have intialized some variables, you can add more if required.

file_count = 0             # file_count to count number of files
files_dict = {}            # files_dic to store count of every file    
unique_word_set = set()    # unique_word_set to store all the unique words in a set
unique_word_dict = {}      # unique_word_dict to store all the unique words appearence in files   

In [4]:
#Your code starts here   
dict_name = "Files"       #Please enter path name Files attached in zip folder
for path in os.listdir(dict_name):
    if os.path.isfile((os.path.join(dict_name, path))):
        if(fnmatch.fnmatch(path,"*.txt")): # To only check files with .txt extension. To count other files remove this statement
            files_dict[path] = file_count
            file_count += 1
#Your code ends here  

Displaying the count of files.

In [5]:
print("\nTotal Number  of files\n", file_count)


Total Number  of files
 3


Displaying Dictionary containing all files.

In [6]:
print("\nDictionary containing  files\n", files_dict)


Dictionary containing  files
 {'f1.txt': 0, 'f2.txt': 1, 'f3.txt': 2}


# Step 3 Extract Unique Vocabulary

In [7]:
# write code to print all the unique words in every file and store them in a set

In [8]:
#Your code starts here    
print("unique words in files\n")
for path in os.listdir(dict_name):
    with open((os.path.join(dict_name, path)), 'r') as f:
        for line in f: 
            for word in line.split():
                unique_word_set.add(word)  
print(unique_word_set)
print("\ncount of files ",file_count)
#Your code ends here

unique words in files

{'pen', 'is', 'my', 'book', 'this', 'interesting'}

count of files  3


### Expected Output

<img src="4.png"/>

# Step 4 Create Term Document Matrix

Create Term-Doc-matrix using Bag of word approach.and display its contents initially and finally.

In [9]:
# Create Term doc matrix such that colmns will be unique words and all the files will be rows
# Write code to count all the unique words appearances in all the files and store it in a dictionary for words 

In [10]:
#Your code starts here
def setTodict(set1):
    dict1 = {}
    dict1=dict.fromkeys(set1,0)    # converting set into dictionary and storing 0 in all value
    i = -1
    for word in dict1:
        i += 1
        dict1[word] = i
    return dict1 
    
print("TERM DOC MATRIX INITIALLY")
TERM_DOC_MATRIX = np.zeros((file_count,len(unique_word_set)))
print(TERM_DOC_MATRIX)

print("\ndictionary of unique words")       
unique_word_dict = setTodict(unique_word_set)      #calling function that count all unique words appea      
print(unique_word_dict)                

print("\ndictionary of files")
print(files_dict)
#Your code ends here

TERM DOC MATRIX INITIALLY
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

dictionary of unique words
{'pen': 0, 'is': 1, 'my': 2, 'book': 3, 'this': 4, 'interesting': 5}

dictionary of files
{'f1.txt': 0, 'f2.txt': 1, 'f3.txt': 2}


### Expected Output

<img src="5.png"/>

# Step 5 Fill Term Document Matrix

In [11]:
# Fill the term doc matrix by checking if the unique word exists in a file or not
# If it exists then substitute a 1 in term_doc_matrix (eg : TERM_DOC_MATRIX[file][word] = 1 ) 
# Do the same for all the files present in the directory

In [12]:
#Your code starts here
file = -1                  # to keep track of file number in TERM_DOC_MATRIX
print("TERM DOC MATRIX after filling")
for path in os.listdir(dict_name):
    with open((os.path.join(dict_name, path)), 'r') as f:
        lst =[]
        file+=1
        for line in f:
            for word in line.split():
                lst.append(word) 
            count = -1                         # to keep track of word in TERM_DOC_MATRIX
            for unique_word in unique_word_set:
                count +=1
                if unique_word in lst:
                    TERM_DOC_MATRIX[file][count] = 1
                else:
                    TERM_DOC_MATRIX[file][count] = 0                
print(TERM_DOC_MATRIX) 
print("col vector(initially)")
#Your code ends here            

TERM DOC MATRIX after filling
[[0. 1. 1. 1. 1. 0.]
 [1. 1. 1. 0. 1. 0.]
 [0. 1. 1. 1. 0. 1.]]
col vector(initially)


### Expected Output

<img src="6.png"/>

# Step 6 Ask for a user Query

In [13]:
# For user query make a column vector of length of all the unique words present in a set

In [14]:
#Your code starts here   
print("col vector(initially)\n")
col_vector = np.array([0 for word in unique_word_set]).reshape(len(unique_word_set),1)
print(col_vector)          # To make column vector
#Your code ends here

col vector(initially)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]]


### Expected Output

<img src="7.png"/>

In [15]:
query = input("\nWrite something for searching  ")
# Check every word of query if it exists in the set of unique words or not
# If exixts then increment the count of that word in word dictionary


Write something for searching  this book is interesting


In [16]:
#Your code starts here  
print("col vector(after filling)")
i=0
for word in query.split():
    for unique_word in unique_word_set:
        if word == unique_word:
            i = list(unique_word_dict.keys()).index(word)   # store indexes of
            col_vector[i] += 1
        else:
            continue
print(col_vector)   
#Your code ends here

col vector(after filling)
[[0]
 [1]
 [0]
 [1]
 [1]
 [1]]


### Expected Output

<img src="8.png"/>

# Step 7 Display Resultant Vector

Display 
1. Resultant vector.
2. Max value in resultant vector.
3. Index of max value in resultant vector.


In [17]:
#Your code starts here  
index = 0                     # to store index of max value in resultant vector
resultant_vector = np.dot(TERM_DOC_MATRIX,col_vector)
print(resultant_vector)
#max_value = np.amax(resultant_vector)
max_value = resultant_vector[0]
for i in range(len(resultant_vector)):
    if(resultant_vector[i] > max_value):
        index = i
        max_value = resultant_vector[i]
        
print("\nMaximum in resultant is ",max_value[0])
print("\nIndex of maximum in resultant is ",index)
#Your code ends here

[[3.]
 [2.]
 [3.]]

Maximum in resultant is  3.0

Index of maximum in resultant is  0


### Expected Output

<img src="9.png"/>

# Step 8 Display the contents of file


In [18]:
#Write the code to identify the file_name having maximum value in the resultant vector and display its contents.

In [19]:
#Your code starts here    
file_no = index 
for key,value in files_dict.items():
    if value == file_no:
        file_name = key
with open((os.path.join(dict_name, file_name)), 'r') as f:
        contents = f.read()
print("File: ",file_name)
print(contents)
#Your code ends here

File:  f1.txt
this is my book


Congratulations Now you are able to build your own small IRS.